drop table facility cascade constraints; 
drop table facility_info cascade constraints;
drop table comments cascade constraints;
drop table preference cascade constraints;
drop table users cascade constraints;
purge recyclebin;

CREATE TABLE facility (
    id                NUMBER(20, 10) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name              VARCHAR2(200) NOT NULL,
    category         VARCHAR2(200) NOT NULL,
    address           VARCHAR2(50) NOT NULL,
    latitude          NUMBER(30, 20) NOT NULL,
    longitude         NUMBER(30, 20) NOT NULL
);
CREATE TABLE facility_info (
    name                          VARCHAR2(200) NOT NULL,
    name_branch                   VARCHAR2(200),
    category1                     VARCHAR2(200) NOT NULL,
    category2                     VARCHAR2(200) NOT NULL,
    category3                     VARCHAR2(200),
    address_region                VARCHAR2(200) NOT NULL,
    address_city                  VARCHAR2(200),
    address_state                 VARCHAR2(200),
    address_province              VARCHAR2(200),
    house_number                  VARCHAR2(200),
    street_name                   VARCHAR2(200),
    building_number               VARCHAR2(200),
    latitude                      NUMBER(30, 20) NOT NULL,
    longitude                     NUMBER(30, 20) NOT NULL,
    postal_code                   VARCHAR2(200),
    road_address                  VARCHAR2(200),
    lot_address                   VARCHAR2(200),
    phone_number                  VARCHAR2(200),
    website                       VARCHAR2(200),
    blog_url                      VARCHAR2(200),
    facebook_url                  VARCHAR2(200),
    instagram_url                 VARCHAR2(200),
    closed_days                   VARCHAR2(200),
    operating_hours               VARCHAR2(300),
    free_parking_available        CHAR(1),
    paid_parking_available        CHAR(1),
    admission_fee                 CHAR(1),
    accessible_entrance           CHAR(1),
    wheelchair_rental_available   CHAR(1),
    accessible_restroom           CHAR(1),
    accessible_parking_available  CHAR(1),
    large_parking_available       CHAR(1),
    guide_dog_accommodation       CHAR(1),
    braille_guide_available       CHAR(1),
    audio_guide_korean            CHAR(1),
    last_updated_date             DATE,
    facility_id                   NUMBER(20, 10) NOT NULL PRIMARY KEY,
    FOREIGN KEY ( facility_id ) REFERENCES facility ( id )
);

CREATE TABLE users (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    userid    VARCHAR2(50) NOT NULL UNIQUE,
    username  VARCHAR2(50) NOT NULL,
    email     VARCHAR2(50) NOT NULL UNIQUE,
    password  VARCHAR2(200) NOT NULL
);

CREATE TABLE comments (
    id           NUMBER(20, 10) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    content      CLOB NOT NULL,
    createdat    DATE NOT NULL,
    createdby    CHAR(50) NOT NULL,
    modifiedat   DATE,
    facility_id  INTEGER NOT NULL,
    users_id     INTEGER NOT NULL,
    FOREIGN KEY (facility_id) REFERENCES facility(id),
    FOREIGN KEY (users_id) REFERENCES users ( id )
);

CREATE TABLE preference (
    id           NUMBER(20, 10) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    liked        CHAR(1),
    facility_id  INTEGER NOT NULL,
    users_id     INTEGER NOT NULL,
    FOREIGN KEY ( facility_id ) REFERENCES facility ( id ),
    FOREIGN KEY ( users_id ) REFERENCES users ( id )
);

INSERT INTO facility (name, address, latitude, longitude)
VALUES ('Sample Facility Info', 'Sample Facility Info address', 37.56804459, 127.01089);

INSERT INTO users (userid, username, email, password)
VALUES ('user1', 'User One', 'user1@example.com', 'hashed_password_1');

INSERT INTO facility_info (
    name, name_branch, category1, category2, category3,
    address_region, address_city, address_state, address_province,
    house_number, street_name, building_number,
    latitude, longitude,
    postal_code, road_address, lot_address,
    phone_number, website, blog_url,
    facebook_url, instagram_url,
    closed_days, operating_hours,
    free_parking_available, paid_parking_available,
    admission_fee, accessible_entrance,
    wheelchair_rental_available, accessible_restroom,
    accessible_parking_available, large_parking_available,
    guide_dog_accommodation, braille_guide_available,
    audio_guide_korean, last_updated_date,
    facility_id
)
SELECT
    'Sample Facility Info', 'Branch A', 'Category X', 'Subcategory 1', 'Subcategory 2',
    'Region Alpha', 'City Beta', 'State Gamma', 'Province Delta',
    '123', 'Sample Street', 'Building Z',
    37.12345678901234567890, -122.12345678901234567890,
    '54321', '456 Sample Road', 'Block 10, Lot 20',
    '987-654-3210', 'www.samplefacilityinfo.com', 'samplefacilityinfo.blog',
    'samplefacilityinfo_facebook', 'samplefacilityinfo_instagram',
    'Monday to Friday', '9:00 AM - 6:00 PM',
    'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N',
    f.id -- facility_id
FROM
    facility f
WHERE
    f.name = 'Sample Facility Info';

INSERT INTO preference (liked, facility_id, users_id)
VALUES ('Y', 1, 1);

INSERT INTO comments (content, createdat, createdby, modifiedat, facility_id, users_id)
VALUES (
    'This is a sample comment.',
    SYSDATE,
    'user1',
    NULL,
    1,
    1
);

--select * from facility;
--select * from users;
--select * from facility_info;
--select * from preference;
-- select * from comments;